#pragma once
/* Stable view IDs shared by navigation and persisted notifications. Append only. */
typedef enum {
    APP_VIEW_DESKTOP=0, APP_VIEW_CLOCK, APP_VIEW_WEATHER, APP_VIEW_SETTINGS,
    APP_VIEW_WIFI, APP_VIEW_REMOTE, APP_VIEW_BLUETOOTH, APP_VIEW_AVATAR,
    APP_VIEW_QUOTA, APP_VIEW_CODEX_RESET, APP_VIEW_MUSIC, APP_VIEW_RADIO,
    APP_VIEW_WALLPAPER_STUDIO, APP_VIEW_OVERVIEW, APP_VIEW_AGENTS, APP_VIEW_NOTES,
    APP_VIEW_STARS, APP_VIEW_ENGLISH, APP_VIEW_LIBRARY, APP_VIEW_PET,
    APP_VIEW_STORY, APP_VIEW_FLIP, APP_VIEW_COUNT
} app_view_t;
