// Generated by tools/build_english_assets.py. Do not hand edit.
#pragma once
#include <stdint.h>
#define ENGLISH_WORD_COUNT 12
typedef struct { const char *word,*chinese,*category; uint32_t image,thumbnail,audio,audio_bytes,image_bytes,thumbnail_bytes; } english_asset_t;
static const english_asset_t english_assets[ENGLISH_WORD_COUNT] = {
    {"cat","猫","动物",0,10246,15988,19074,10246,5740},
    {"dog","狗","动物",35064,44556,49804,16446,9492,5245},
    {"bird","鸟","动物",66252,72507,76020,15228,6255,3512},
    {"fish","鱼","动物",91248,102398,108376,19796,11150,5975},
    {"apple","苹果","水果",128172,138491,144524,19274,10319,6031},
    {"banana","香蕉","水果",163800,169348,172588,21340,5548,3239},
    {"orange","橙子","水果",193928,205932,212480,21760,12004,6548},
    {"strawberry","草莓","水果",234240,248746,256888,29116,14506,8139},
    {"ball","球","物品",286004,299040,306436,15970,13036,7396},
    {"car","汽车","物品",322408,333159,339328,17216,10751,6166},
    {"book","书","物品",356544,368204,374840,15228,11660,6634},
    {"cup","杯子","物品",390068,399178,404424,18702,9110,5243},
};
