"""Compile reviewed MiniMax atlases and local TTS into a bounded flash pack.

Only deterministic crop/resize/PCM format conversion; no runtime downloads.
Reuses existing audio so rebuilding pictures does not change pronunciations.
"""
import array
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import zlib
from PIL import Image, ImageDraw

ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/'main/assets/english'
SOURCES={
    'animals':'animals/minimax-image-20260916-093843-bdefb6f0.jpg',
    'fruit':'fruit/minimax-image-20260916-093922-5e367a49.jpg',
    'objects':'objects/minimax-image-20260916-093956-07c6a40f.jpg',
    'orange':'orange/minimax-image-20260916-094148-73ee9edc.jpg',
}
WORDS=[('cat','猫','动物','animals',0),('dog','狗','动物','animals',1),
       ('bird','鸟','动物','animals',2),('fish','鱼','动物','animals',3),
       ('apple','苹果','水果','fruit',0),('banana','香蕉','水果','fruit',1),
       ('orange','橙子','水果','orange',0),('strawberry','草莓','水果','fruit',3),
       ('ball','球','物品','objects',0),('car','汽车','物品','objects',1),
       ('book','书','物品','objects',2),('cup','杯子','物品','objects',3)]

def picture(source,cell,size):
    image=Image.open(ASSETS/'source'/SOURCES[source]).convert('RGB')
    if source!='orange':
        w,h=image.size
        image=image.crop((cell%2*w//2,cell//2*h//2,(cell%2+1)*w//2,(cell//2+1)*h//2))
    # Remove empty atlas margins, not object details. White padding makes every
    # object legible at the same visual scale without stretching its shape.
    mask=Image.new('L',image.size)
    mask.putdata([255 if min(p)<225 and max(p)-min(p)>18 else 0 for p in image.getdata()])
    box=mask.getbbox()
    if not box: raise ValueError('empty picture: '+source)
    x0,y0,x1,y1=box; pad=18
    image=image.crop((max(0,x0-pad),max(0,y0-pad),min(image.width,x1+pad),min(image.height,y1+pad)))
    image.thumbnail((size-12,size-12),Image.Resampling.LANCZOS)
    result=Image.new('RGB',(size,size),'white')
    result.paste(image,((size-image.width)//2,(size-image.height)//2))
    return result

def rgb565(image):
    pixels=image.get_flattened_data() if hasattr(image,'get_flattened_data') else image.getdata()
    result=array.array('H',[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b in pixels])
    if sys.byteorder!='little': result.byteswap()
    return result.tobytes()

def main():
    (ASSETS/'audio').mkdir(parents=True,exist_ok=True)
    (ASSETS/'cards').mkdir(exist_ok=True)
    artifact=ROOT/'artifacts/english'; artifact.mkdir(parents=True,exist_ok=True)
    pack=bytearray(); records=[]; declarations=[]
    sheet=Image.new('RGB',(4*200,3*224),'white'); draw=ImageDraw.Draw(sheet)
    for index,(word,chinese,category,source,cell) in enumerate(WORDS):
        pcm=ASSETS/'audio'/f'{word}.pcm'
        if not pcm.exists():
            aiff=ASSETS/'audio'/f'{word}.aiff'
            subprocess.run(['/usr/bin/say','-v','Samantha','-r','135','-o',str(aiff),word+'.'],check=True)
            subprocess.run(['/opt/homebrew/bin/ffmpeg','-y','-loglevel','error','-i',str(aiff),
                '-ar','16000','-ac','1','-af','volume=0.65,apad=pad_dur=0.12','-f','s16le',str(pcm)],check=True)
        sound=pcm.read_bytes()
        assert 3200<=len(sound)<=128000 and len(sound)%2==0,word
        offsets=[]; lengths=[]
        for size in (176,128):
            offsets.append(len(pack)); image=picture(source,cell,size)
            compressed=zlib.compress(rgb565(image),9); lengths.append(len(compressed)); pack.extend(compressed)
            if size==176:
                image.save(ASSETS/'cards'/f'{word}.png')
                x=(index%4)*200; y=(index//4)*224
                sheet.paste(image,(x+12,y)); draw.text((x+12,y+180),word,fill='black')
        while len(pack)%4: pack.append(0)
        offsets.append(len(pack)); pack.extend(sound)
        while len(pack)%4: pack.append(0)
        records.append(dict(word=word,chinese=chinese,category=category,source=SOURCES[source],cell=cell,
                            imageOffset=offsets[0],thumbnailOffset=offsets[1],imageBytes=lengths[0],thumbnailBytes=lengths[1],audioOffset=offsets[2],
                            audioBytes=len(sound),audioSeconds=len(sound)/32000))
        declarations.append('    {"%s","%s","%s",%d,%d,%d,%d,%d,%d},'%(word,chinese,category,*offsets,len(sound),*lengths))
    (ASSETS/'english.bin').write_bytes(pack)
    (ROOT/'main/english_assets.h').write_text(
        '// Generated by tools/build_english_assets.py. Do not hand edit.\n#pragma once\n'
        '#include <stdint.h>\n#define ENGLISH_WORD_COUNT 12\n'
        'typedef struct { const char *word,*chinese,*category; uint32_t image,thumbnail,audio,audio_bytes,image_bytes,thumbnail_bytes; } english_asset_t;\n'
        'static const english_asset_t english_assets[ENGLISH_WORD_COUNT] = {\n'+'\n'.join(declarations)+'\n};\n')
    (ASSETS/'manifest.json').write_text(json.dumps({'provider':'MiniMax image-01','voice':'macOS Samantha en_US, 135 wpm',
        'format':'zlib RGB565 LE 176x176 + 128x128; PCM16 LE mono 16000 Hz',
        'packBytes':len(pack),'sha256':hashlib.sha256(pack).hexdigest(),'words':records},ensure_ascii=False,indent=2))
    sheet.save(artifact/'all-cards.png')
    print('12 reviewed cards and pronunciations; flash pack bytes:',len(pack))

if __name__=='__main__': main()
